spring:
  application:
    name: account-service

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9004/eureka/


---
spring:
  profiles: container

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9004/eureka/