spring:
  application:
    name: customer-service

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9004/eureka/

---
spring:
  profiles: container

accountContextRoot:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9004/eureka/