language: java
sudo: required
services:
- docker
jdk:
- oraclejdk8
install:
- mvn install -P war
notifications:
  slack:
    secure: e6ek7WTuikUEt58Em+jC89MZG+uufvHv/wJjMixDw3O2/yzicjf3dPxUazKQ3dpBieVeOrvQvucFvExybxVy+Ps2pZxEX22jABsvCGP7RncGvSZKecg7o9EOijN/37qAoAPUVr6Bxx9VimTeur2y8oG1+9gyNFkiLnGB7Wjm3AlbqGPaNhkrGNvi7b6QSZ+4xXZhq6oK/h1BAbWhviKpvBAdBtMGLOmjhrygdeMg69a2vwcgW3wdr/XwirFUgGFciUhw07gIqoZIkhqOm6MqYWyr43hLdwVDjU/qwY/wSNs/JYFOTGERy6IVI7p0NxUCEK+lZuhoNLOiTvETSybe6P4gGmA/CmsFCunJjXdPnh3Zeu8NlbP0Cff8TOLw+kT9h+9xYoZJAWIHxfqX69p+m50K0yWW7c8MeOnxZYurxDZmRF4JCkuZQa8kraIy+AE7+aZ2ZtEmj1+NOnEPrULF5mQaob+4rLv8EYnbOHoGI8ZSppE7f4VF1kMUPny7Y0f+2jYAzXzFK6BlLsDPediu/tQ6UEjlbJ2brUIABRpiTGDTrUbePPQNY5QsCr/iuOcnkAslwPZ0QtNZHK6waQTn/QRV6GN5eOZ5FMyb+Jm3BdmnCpUmnvT2KHyO3rOk5d6kl5DVXg84GCRqPvT8LzkzHBZ36QxVU/qrFGoVk7PswmA=
