services:
  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    build: ./liquibase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
    depends_on:
      - postgres

  book:
    build: ./book
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb?currentSchema=spring_cloud_app
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
    depends_on:
      - postgres

  gateway:
    build: ./gateway
    depends_on:
      - book
      - customer
      - account
    ports:
      - "8082:8080"

  account:
    build: ./account
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb?currentSchema=spring_cloud_app
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
    depends_on:
      - postgres

  customer:
    build: ./customer
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb?currentSchema=spring_cloud_app
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
    depends_on:
      - postgres

volumes:
  pgdata: