### Book Service /available
GET http://localhost:8082/book/available

### Book Service /checked-out
GET http://localhost:8082/book/checked-out

### Account Service /accounts
GET http://localhost:8082/account/accounts

### Account Service /accounts/customer
GET http://localhost:8082/account/accounts/customer/1

### Account Service /accounts/{accountNumber}
GET http://localhost:8082/account/accounts/111111

### Customer Service /customers
GET http://localhost:8082/customer/customers

### Customer Service /customers/pesel/
GET http://localhost:8082/customer/customers/pesel/12345