spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: "*" # Or specific endpoints like health, info, restart, shutdown
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always # Or when_authorized if security is configured

server:
  port: 8080