spring:
  application:
    name: registry

server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9004/eureka/

---
spring:
  profiles: container

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:9004/eureka/
