spring:
  jmx:
    enabled: false

accountContextRoot: account-service

server:
  hostname: localhost
  port: 8080

eureka:
  instance:
    statusPageUrlPath: /${spring.application.name}/actuator/info
    healthCheckUrlPath: /${spring.application.name}/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/